// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindflow_backend.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace Mindflow_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616000000_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mindflow_backend.iam.domain.model.aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<bool>("PausedByAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("paused_by_ai");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("streak");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_habits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_habits_user_id");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Entities.HabitCompletionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("int")
                        .HasColumnName("habit_id");

                    b.Property<string>("HabitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("habit_name");

                    b.HasKey("Id")
                        .HasName("p_k_habit_completion_logs");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("i_x_habit_completion_logs_habit_id");

                    b.ToTable("habit_completion_logs");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("HasPreview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_preview");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sentiment");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_journal_entries");

                    b.ToTable("journal_entries");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_tags");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.EntryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("entry_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("p_k_entry_tags");

                    b.HasIndex("EntryId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("i_x_entry_tags_entry_id_tag_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("i_x_entry_tags_tag_id");

                    b.ToTable("entry_tags");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("entry_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_media");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("i_x_media_entry_id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("Mindflow_backend.Analytics.Domain.Entities.AnalyticsCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AiInsight")
                        .HasColumnType("text")
                        .HasColumnName("ai_insight");

                    b.Property<string>("AiInsightLocalized")
                        .HasColumnType("text")
                        .HasColumnName("ai_insight_localized");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FluctuationData")
                        .HasColumnType("json")
                        .HasColumnName("fluctuation_data");

                    b.Property<string>("Kpis")
                        .HasColumnType("json")
                        .HasColumnName("kpis");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TrendData")
                        .HasColumnType("json")
                        .HasColumnName("trend_data");

                    b.Property<string>("TrendPercentage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("trend_percentage");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id")
                        .HasName("p_k_analytics_caches");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("i_x_analytics_caches_user_id_week_start");

                    b.ToTable("analytics_caches");
                });

            modelBuilder.Entity("Mindflow_backend.Analytics.Domain.Entities.WordCloud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Words")
                        .HasColumnType("json")
                        .HasColumnName("words");

                    b.HasKey("Id")
                        .HasName("p_k_word_clouds");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_word_clouds_user_id");

                    b.ToTable("word_clouds");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Entities.HabitCompletionLog", b =>
                {
                    b.HasOne("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", null)
                        .WithMany("CompletionLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_habit_completion_logs_habits_habit_id");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.EntryTag", b =>
                {
                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.JournalEntry", "Entry")
                        .WithMany("EntryTags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_entry_tags_journal_entries_entry_id");

                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_entry_tags_tags_tag_id");

                    b.Navigation("Entry");
                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Media", b =>
                {
                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.JournalEntry", "Entry")
                        .WithMany("Media")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_media_journal_entries_entry_id");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", b =>
                {
                    b.Navigation("CompletionLogs");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("EntryTags");
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
